#!/bin/sh
INT=`networksetup -listallhardwareports | awk '/Hardware Port: Wi-Fi/,/Ethernet/' | awk 'NR==2' | cut -d " " -f 2`
echo "<result>$(networksetup -listpreferredwirelessnetworks $INT | grep MLP-GUEST)</result>"

